### PR TITLE
Use branch v2.3.2 of adjust/redis

### PR DESCRIPTION
**Pull request by andrewslotin**

### CODE REVIEW

**Comment by wellle** [comment]
Done.

**Comment by elmacnifico** [comment]
I would not advice using this commit for "faster write method"....
It's very outdated and employs a quite frankly stupid strategy (yes i wrote that...)

**Comment by elmacnifico** [comment]
Use this here instead

https://github.com/adjust/redisio/blob/master/writer.go

**Comment by wellle** [comment]
@elmacnifico: We didn't merge this branch, but we are still using this one which contains the commit you reference: https://github.com/adjust/goenv/commits/add-redis-log

If that shouldn't be used, please open a PR against the `add-redis-log`.

**Comment by elmacnifico** [comment]
Done

https://github.com/adjust/goenv/pull/18

Please test this on a single backend first. I am very confident that this reduces CPU load for the logging redis significantly.
But this goenv branch is used in all of the backend currently, so we need to test this first :wink:

**Comment by elmacnifico** [comment]
@roa @wellle

**Pull request closed without merging**
